=head1 Hafni

Hafni is a java swing wrapper for the clojure language focusing on how components change.

=head2 Usage

See [Wiki/usage](https://github.com/odyssomay/Hafni/wiki/Usage)

=head2 Installation

Not currently possible - download the source.

=head2 Reference

To the left is the java class or "functionality", to the right is the function used.

=head3 Hafni.swing.action

 AbstractAction		action
 ButtonGroup		button-group
 JButton		button
 JCheckBox		check-box
 JCheckBoxMenuItem	check-box-menu-item
 JMenuItem		menu-item
 JRadioButton		radio-button
 JRadioButtonMenuItem	radio-button-menu-item
 JToggleButton		toggle-button

=head3 Hafni.swing.container

 JComboBox 		combo-box
 JSpinner		spinner

=head3 Hafni.swing.dialog

 JOptionPane/showMessageDialog
			message
			info-message
			warning-message
			error-message
			plain-message
 JOptionPane/showInputDialog
			text-input-dialog
			adv-input-dialog

=head3 Hafni.swing.layout

 BorderLayout		border-layout
 BoxLayout		box-layout
 CardLayout		card-layout
 FlowLayout		flow-layout

=head3 Hafni.swing.menu

 JMenu			menu
 JMenuBar		menu-bar
 JToolBar		tool-bar

=head3 Hafni.swing.text

 JPasswordField		password-field
 JTextArea		text-area
 JTextField		text-field
 JTextPane		text-pane

=head3 Hafni.swing.view

 JFrame			frame
 JIcon			icon
 JLabel 		label

